#!/usr/bin/env bash
set -Eeuo pipefail
adbx shell pm enable --user 0 com.google.android.gm
adbx shell pm enable --user 0 com.google.android.apps.maps
adbx shell pm enable --user 0 com.google.android.apps.photos
adbx shell pm enable --user 0 com.google.android.youtube
adbx shell pm enable --user 0 com.google.android.apps.youtube.music
adbx shell pm enable --user 0 com.android.chrome
adbx shell pm enable --user 0 com.google.android.apps.docs
adbx shell pm enable --user 0 com.google.android.videos
adbx shell pm enable --user 0 com.google.android.googlequicksearchbox
adbx shell pm enable --user 0 com.android.hotwordenrollment.okgoogle
adbx shell pm enable --user 0 com.android.hotwordenrollment.xgoogle
adbx shell pm enable --user 0 com.google.android.apps.bard
adbx shell pm enable --user 0 com.google.android.apps.turbo
adbx shell pm enable --user 0 com.google.ar.core
adbx shell pm enable --user 0 com.google.android.projection.gearhead
adbx shell pm enable --user 0 com.samsung.android.app.tips
adbx shell pm enable --user 0 com.samsung.android.app.spage
adbx shell pm enable --user 0 com.samsung.sree
adbx shell pm enable --user 0 com.samsung.android.game.gamehome
adbx shell pm enable --user 0 com.samsung.android.game.gametools
adbx shell pm enable --user 0 com.samsung.android.game.gos
adbx shell pm enable --user 0 com.samsung.android.aremoji
adbx shell pm enable --user 0 com.samsung.android.aremojieditor
adbx shell pm enable --user 0 com.sec.android.app.kidshome
adbx shell pm enable --user 0 com.samsung.android.kidsinstaller
adbx shell pm enable --user 0 com.sec.android.app.quicktool
adbx shell pm enable --user 0 com.samsung.mediasearch
adbx shell pm enable --user 0 com.samsung.ecomm.global.gbr
adbx shell pm enable --user 0 com.samsung.android.app.parentalcare
adbx shell pm enable --user 0 com.samsung.android.app.readingglass
adbx shell pm enable --user 0 com.samsung.android.app.routines
adbx shell pm enable --user 0 com.samsung.android.smartmirroring
adbx shell pm enable --user 0 com.samsung.android.aicore
adbx shell pm enable --user 0 com.samsung.android.bixby.agent
adbx shell pm enable --user 0 com.samsung.android.bixby.wakeup
adbx shell pm enable --user 0 com.samsung.android.bixbyvision.framework
adbx shell pm enable --user 0 com.samsung.android.visionintelligence
adbx shell pm enable --user 0 com.samsung.android.intellivoiceservice
adbx shell pm enable --user 0 com.facebook.katana
adbx shell pm enable --user 0 com.facebook.appmanager
adbx shell pm enable --user 0 com.facebook.services
adbx shell pm enable --user 0 com.facebook.system
adbx shell pm enable --user 0 com.linkedin.android
adbx shell pm enable --user 0 com.netflix.mediaclient
adbx shell pm enable --user 0 com.microsoft.skydrive
adbx shell pm enable --user 0 com.microsoft.office.officehubrow
adbx shell pm enable --user 0 com.microsoft.office.outlook
adbx shell pm enable --user 0 com.spotify.music
adbx shell pm enable --user 0 com.hiya.star
adbx shell pm enable --user 0 com.sec.android.diagmonagent
adbx shell pm enable --user 0 com.samsung.android.dqagent
